// Scrubbing on the customer's machine: identical tokens to AgentCompile's server and the Python
// SDK (shared vectors, generated by the server's own scrubber), applied before sending.

import { mkdtempSync, readFileSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import OpenAI from "openai";
import { afterEach, describe, expect, it } from "vitest";
import { flush, wrap } from "../src/index.js";
import { loadScrubKey, scrubCall, scrubText, scrubToolOutput, scrubValue } from "../src/scrub.js";

interface Case<T> {
  input: T;
  output: T;
}
const VECTORS: {
  key: string;
  text: Case<string>[];
  value: Case<unknown>[];
  tool_output: Case<string>[];
} = JSON.parse(readFileSync(new URL("./data/scrub-vectors.json", import.meta.url), "utf8"));
const KEY = Buffer.from(VECTORS.key);

describe("the same tokens as the server", () => {
  it.each(VECTORS.text)("text: $input", ({ input, output }) => {
    expect(scrubText(input, KEY)).toBe(output);
  });
  it.each(VECTORS.value)("value %#", ({ input, output }) => {
    expect(scrubValue(input, KEY)).toEqual(output);
  });
  it.each(VECTORS.tool_output)("tool output: $input", ({ input, output }) => {
    expect(scrubToolOutput(input, KEY)).toBe(output);
  });
});

describe("the key", () => {
  const saved = { ...process.env };
  afterEach(() => {
    process.env = { ...saved };
  });

  it("comes from the environment", () => {
    process.env.AGENTCOMPILE_SCRUB_KEY = "fleet-key";
    expect(loadScrubKey().toString()).toBe("fleet-key");
  });

  it("is otherwise created once, owner-only", () => {
    delete process.env.AGENTCOMPILE_SCRUB_KEY;
    const home = mkdtempSync(join(tmpdir(), "ack-"));
    process.env.AGENTCOMPILE_HOME = home;
    const first = loadScrubKey();
    expect(first.length).toBe(64);
    expect(loadScrubKey().equals(first)).toBe(true);
    expect(statSync(join(home, "scrub.key")).mode & 0o777).toBe(0o600);
  });
});

const MESSAGES = [
  { role: "user", content: "I'm mia@example.com, card 4111 1111 1111 1111" },
  {
    role: "assistant",
    content: null,
    tool_calls: [
      {
        id: "t1",
        type: "function",
        function: { name: "find_user", arguments: '{"email": "mia@example.com"}' },
      },
    ],
  },
  { role: "tool", tool_call_id: "t1", content: '{"user_id": "u1", "phone": "415-555-0199"}' },
];

async function send(scrub: boolean): Promise<any[]> {
  process.env.AGENTCOMPILE_SCRUB_KEY = VECTORS.key;
  const sent: any[] = [];
  const agentcompile: typeof fetch = async (input, init) => {
    if (String(input).endsWith("/v1/capture")) {
      sent.push(...JSON.parse(String(init?.body)).exchanges);
      return new Response("{}", { status: 200 });
    }
    return new Response(JSON.stringify({ action: "forward", reason: "x" }), { status: 200 });
  };
  const provider: typeof fetch = async () =>
    new Response(
      JSON.stringify({
        id: "c1",
        object: "chat.completion",
        created: 0,
        model: "m",
        choices: [
          {
            index: 0,
            message: { role: "assistant", content: "Done, mia@example.com" },
            finish_reason: "stop",
          },
        ],
      }),
      { status: 200, headers: { "content-type": "application/json" } },
    );
  const client = wrap(new OpenAI({ apiKey: "sk", baseURL: "http://p.test/v1", fetch: provider }), {
    baseUrl: "http://ac.test",
    trail: false,
    capture: true,
    scrub,
    fetch: agentcompile,
  });
  await client.chat.completions.create({
    model: "m",
    messages: MESSAGES,
    conversation_id: "c1",
  } as any);
  await flush();
  return sent;
}

describe("captured calls", () => {
  it("leave the machine scrubbed, with matching tokens", async () => {
    const [record] = await send(true);
    const text = JSON.stringify(record);
    expect(text).not.toContain("mia@example.com");
    expect(text).not.toContain("4111 1111 1111 1111");
    expect(text).not.toContain("415-555-0199");
    const email = scrubText("mia@example.com", KEY);
    const messages = record.request.messages;
    expect(messages[0].content).toContain(email);
    expect(JSON.parse(messages[1].tool_calls[0].function.arguments)).toEqual({ email });
    expect(JSON.parse(messages[2].content).user_id).toBe("u1");
    expect(record.response.choices[0].message.content).toContain(email);
    expect(record.scrubbed).toBe(true);
  });

  it("are sent as they are with scrub: false", async () => {
    const [record] = await send(false);
    expect(JSON.stringify(record)).toContain("mia@example.com");
    expect(record.scrubbed).toBeUndefined();
  });
});

describe("edge cases", () => {
  it("writes non-ASCII the way Python does", () => {
    expect(scrubToolOutput('{"name": "José ☕", "e": "a@b.co"}', KEY)).toBe(
      `{"name": "Jos\\u00e9 \\u2615", "e": "${scrubText("a@b.co", KEY)}"}`,
    );
  });

  it("writes every JSON value type the way Python does", () => {
    const out = scrubToolOutput('{"a":[1,2.5,true,false,null],"b":{"c":"x"}}', KEY);
    expect(out).toBe('{"a":[1,2.5,true,false,null],"b":{"c":"x"}}');
  });

  it("scrubs a plain-text tool output as text", () => {
    expect(scrubToolOutput("reach me at a@b.co", KEY)).toBe(
      `reach me at ${scrubText("a@b.co", KEY)}`,
    );
  });

  it("scrubs a whole call, nested", () => {
    const call = scrubCall({ messages: [{ content: "a@b.co" }], n: 3, ok: true }, KEY) as any;
    expect(call.messages[0].content).toBe(scrubText("a@b.co", KEY));
    expect(call.n).toBe(3);
    expect(call.ok).toBe(true);
  });

  it("leaves short and non-card numbers alone", () => {
    expect(scrubText("1234 5678 9012 3456 is not a card", KEY)).toBe(
      "1234 5678 9012 3456 is not a card",
    );
    expect(scrubValue({ phone: "12" }, KEY)).toEqual({ phone: "12" });
  });
});
